language: node

cache: yarn

before_install:
    - pip install --user hererocks
    - hererocks lua53 -l5.3 -rlatest --cflags="-DLUA_INT_TYPE=LUA_INT_INT"
    - source lua53/bin/activate
    - nvm install node
    - export NODE=$(nvm which node)
    - export NPM=${NODE%node}npm
    - $NPM install -g yarn

install:
    - yarn

script:
    - yarn build
    - travis_wait yarn test

notifications:
    email: false
