language: node

cache: yarn

before_install:
    - nvm install node
    - export NODE=$(nvm which node)
    - export NPM=${NODE%node}npm
    - $NPM install -g yarn

install:
    - yarn

script:
    - yarn lint
    - FENGARICONF='{"LUAI_MAXSTACK":100000}' travis_wait yarn test

notifications:
    email: false
